apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akatsuki-pypi-api-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: akatsuki-pypi-api-volume
